# Android Handler
if (CMAKE_SYSTEM_NAME STREQUAL "Android" OR CMAKE_CXX_COMPILER_ID MATCHES "Clang" OR (CMAKE_CXX_COMPILER MATCHES "android" OR CMAKE_C_COMPILER MATCHES "android") OR ANDROID)
    message(STATUS "Target build is Android")
    set(APP_TARGETS_ANDROID ON)
else()
    set(APP_TARGETS_ANDROID OFF)
endif ()

# Global Cross-Toolchains
if (DEFINED APP_CONFIG_TARGET AND APP_CONFIG_TARGET)
    if (EXISTS "${CMAKE_SOURCE_DIR}/Toolchains/${APP_CONFIG_TARGET}.cmake")
        include("${CMAKE_SOURCE_DIR}/Toolchains/${APP_CONFIG_TARGET}.cmake")
    else ()
        message(FATAL_ERROR "Toolchain file '${APP_CONFIG_TARGET}.cmake' does not exist.\nMake sure that the Toolchain file exists.")
    endif ()
else ()
    if (UNIX AND NOT APPLE AND NOT APP_TARGETS_ANDROID)
        set(APP_SYSTEM_TARGET "Linux")
    elseif (WIN64 OR MINGW)
        set(APP_SYSTEM_TARGET "Windows")
    elseif (UNIX AND APP_TARGETS_ANDROID)
        set(APP_SYSTEM_TARGET "Android")
    endif ()

    if (CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64" OR CMAKE_SYSTEM_PROCESSOR STREQUAL "amd64")
        set(APP_SYSTEM_ARCH "x86_64")
    elseif (CMAKE_SYSTEM_PROCESSOR STREQUAL "aarch64" OR CMAKE_SYSTEM_PROCESSOR STREQUAL "arm64")
        set(APP_SYSTEM_ARCH "aarch64")
    else ()
        if (CMAKE_CXX_COMPILER MATCHES "x86_64")
            set(APP_SYSTEM_ARCH "x86_64")
        elseif (CMAKE_CXX_COMPILER MATCHES "aarch64")
            set(APP_SYSTEM_ARCH "aarch64")
        else ()
            find_program(_UNAME_EXEC uname)
            if (_UNAME_EXEC)
                execute_process(
                        COMMAND uname -m
                        OUTPUT_VARIABLE _HOST_ARCH
                        OUTPUT_STRIP_TRAILING_WHITESPACE
                )
            else()
                set(_HOST_ARCH "$ENV{PROCESSOR_ARCHITECTURE}")
            endif()

            if (_HOST_ARCH STREQUAL "x86_64" OR _HOST_ARCH STREQUAL "amd64" OR _HOST_ARCH STREQUAL "AMD64")
                set(APP_SYSTEM_ARCH "x86_64")
            elseif (_HOST_ARCH STREQUAL "aarch64" OR _HOST_ARCH STREQUAL "arm64" OR _HOST_ARCH STREQUAL "ARM64")
                set(APP_SYSTEM_ARCH "aarch64")
            else()
                message(FATAL_ERROR "Unsupported architecture: ${_HOST_ARCH}")
            endif()
        endif ()
    endif ()
endif ()